### ISSUE TITLE
There is a runtime error under frontend server

### ISSUE THREAD

**Issue by OmarQaddourah** [alivx/urless#9]
Error:

```
127.0.0.1 - - [28/Dec/2020 22:26:42] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Dec/2020 22:26:42] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Dec/2020 22:26:42] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Dec/2020 22:26:42] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [28/Dec/2020 22:26:42] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [28/Dec/2020 22:26:48] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/omar/Desktop/SS/urless/env/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/omar/Desktop/SS/urless/env/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/omar/Desktop/SS/urless/env/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/omar/Desktop/SS/urless/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/omar/Desktop/SS/urless/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/omar/Desktop/SS/urless/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/omar/Desktop/SS/urless/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/omar/Desktop/SS/urless/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/omar/Desktop/SS/urless/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/omar/Desktop/SS/urless/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/omar/Desktop/SS/urless/frontend/main.py", line 34, in login
    newShortCode = str(data["short"])
TypeError: 'NoneType' object is not subscriptable

```

**Comment by alivx** [comment]
Fixed :)
